version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ps_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SimplePass}
      PGDATA: /data/postgres
    labels:
      - "traefik.enable=true"
      # routers
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.entryPoints=postgres"
      - "traefik.tcp.routers.postgres.service=postgres"
      # services (needed for TCP)
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5433"
    volumes:
       - postgres:/data/postgres
    #ports:
      #- "5432:5432"
      #- "5433"
    networks:
      #- postgres
      - comonet
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-example@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-SimplePass}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    labels:
      traefik.enable: true
      traefik.docker.network: "comonet"
      traefik.http.routers.pgadmin-postgres.entrypoints: "websecure" 
      traefik.http.routers.pgadmin-postgres.rule: "${PGADMIN_HOST:-example.com}"
      traefik.http.routers.pgadmin-postgres.service: "pgadmin-postgres"
      traefik.http.routers.pgadmin-postgres.middlewares: "ipwhitelist"
      traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange: "${WHITE_LIST}"
    ports:
      #- "${PGADMIN_PORT:-5050}:80"
      - ":5050:80"
    networks:
      #- postgres  
      - comonet
    restart: unless-stopped

networks:
  comonet:                                                                                                                                              
    external:                                                                                                                                    
      name: comonet
#  postgres:
#    driver: bridge

volumes:
    postgres:
    pgadmin:
